### ISSUE TITLE
Can you share the dataset?

### ISSUE THREAD

**Issue by zhaopengfei12345** [wangc1073/multidet#1]

**Comment by wangc1073** [comment]
Thank you for your attention. You can get the dataset from the website: https://cm.asu.edu/ . And the model, multidet, will be released in the coming days.

**Comment by zhaopengfei12345** [comment]
&nbsp;Thanks for your reply. Best regards!



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 26, 2022 21:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wangc1073/multidet] Can you share the dataset? (Issue #1)




 
Thank you for your attention. You can get the dataset from the website: https://cm.asu.edu/ . And the model, multidet, will be released in the coming days.

**Comment by dreamhui** [comment]
Thank you for sharing your code — it has been a great source of inspiration.

Currently, we are unable to access http://cm.asu.edu/
as the site appears to be down. Online searches only yield daily data; hourly-frequency data seems to be unavailable.

I noticed that your code also deals with hourly-level data. Would it be possible for you to provide the original dataset?

Many thanks in advance.
